author:
  email: null
  name: An Author
  twitter: null
  url: null
baseurl: /primer-of-college-football-independent-with-zoom
collections:
  annotations:
    output: true
    permalink: /annotations/:path/
  volume_pages:
    output: true
    permalink: /pages/:path/
defaults:
- scope:
    path: ''
    type: volume_pages
  values:
    deep_zoom: true
    extra_js:
    - volume-page.js
    - hammer.min.js
    - deepzoom.js
    - openseadragon.min.js
    layout: volume_page
    short_label: p.
- scope:
    path: ''
    type: annotations
  values:
    layout: annotation
description: An annotated digital edition created with <a href="http://readux.library.emory.edu/">Readux</a>
gems:
- jekyll-sitemap
homepage_image: images/emory:gnk57/full/,1000/0/default.jpg
image_size:
  page:
    height: 1000
    width: 738
  small-thumbnail:
    height: 100
    width: 73
  thumbnail:
    height: 300
    width: 221
permalink: pretty
publication_info:
  author: Lewis, William H. (William Henry), 1868-1949.
  date: '2017'
  editors:
  - Sara Palmer
  tei_xml: tei.xml
  title: A primer of college football, an annotated digital edition
show_annotation_author: true
source_info:
  author: Lewis, William H. (William Henry), 1868-1949.
  date: '1896'
  pdf_url: https://testreadux.library.emory.edu/books/emory:b670g/pdf/#page=2
  title: A primer of college football
  url: https://testreadux.library.emory.edu/books/emory:b670g/
  via_readux: true
tagline: ', an annotated digital edition'
title: A primer of college football
url: https://sarepal.github.io
version: 0.7
